
server.port=9001
spring.application.name=service1

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Renew every 30 seconds
eureka.client.lease-renewal-interval-in-seconds=30

# Expire after 90 seconds without a renewal
eureka.client.lease-expiration-duration-in-seconds=90

# Enable service deregistration on shutdown
eureka.client.should-deregister-on-shutdown=true

# Health check settings
management.endpoint.health.show-details=always
management.health.status.http-mapping.down=503
management.health.status.http-mapping.up=200
management.health.status.http-mapping.out-of-service=503
